apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloud-builder-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloud-builder-rolebinding
subjects:
  - kind: User
    name: { CLOUD_BUILDER_NAME } # Name must match the `cloud_builder` Kubernetes user name
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cloud-builder-role
  apiGroup: rbac.authorization.k8s.io
