name: Trigger Google Cloud Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - name: Configure gcloud
      run: |
        gcloud config set project PROJECT_ID
        gcloud auth configure-docker

    - name: Trigger Cloud Build
      run: |
        gcloud builds submit --config deploy/cloudbuild.yaml .
