apiVersion: apps/v1
kind: Deployment
metadata:
  name: "prompt-deployment"
spec:
  selector:
    matchLabels:
      app: prompt
  replicas: 1
  template:
    metadata:
      labels:
        app: prompt
    spec:
      containers:
        - name: prompt
          image: ${IMAGE}
          envFrom:
            - configMapRef:
                name: "prompt-configmap"
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: prompt-secrets
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
              ephemeral-storage: 2Gi
            limits:
              cpu: 410m
              memory: "1.5Gi"
              ephemeral-storage: 4Gi
      imagePullSecrets:
        - name: gar
