load("//tools/utils:defs.bzl", "substitution_file")

substitution_file(
    name = "ngnix_conf",
    outs = "auth_ngnix.conf",
    file = "ngnix.conf.tpl",
    substitutions = {
        "AUTH_WEB_EXPOSE_PORT": "$(AUTH_WEB_EXPOSE_PORT)",
        "AUTH_API_PROXY_HOST": "$(AUTH_API_PROXY_HOST)",
        "AUTH_WEB_PROXY_HOST": "$(AUTH_WEB_PROXY_HOST)",
    },
    toolchains = [
        "//sandbox:auth_env_vars",
        "//sandbox:local_dc_env_vars",
    ],
)

sh_binary(
    name = "dc",
    srcs = [
        "//tools/bazel/shell:dc",
    ],
    args = [
        "--env-file $(location {env_vars_file})".format(env_vars_file = "//sandbox:local_dc_env_vars"),
        "--file={package}/docker-compose.development.yml".format(package = package_name()),
    ],
    data = [
        "init-db.sh",
        ":docker-compose.development.yml",
        ":ngnix_conf",
        "//sandbox:local_dc_env_vars",
    ],
    toolchains = [
        "//sandbox:local_dc_env_vars",
    ],
    visibility = ["//visibility:public"],
)
