version: '3.8'

services:
  postgres:
    image: postgres:13.3
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_PASSWORD: pgpass
      AUTH_POSTGRES_DB: ${POSTGRES_DATABASE}
      AUTH_POSTGRES_USER: ${POSTGRES_USERNAME}
      AUTH_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSLMODE: disable

volumes:
  pg_data:
