version: '3.8'

services:
  postgres:
    image: postgres:13.3
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSLMODE: disable

volumes:
  pg_data:
