version: "3.8"

services:
  postgres:
    image: postgres:15.3
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_PASSWORD: pgpass
      AUTH_POSTGRES_DB: ${POSTGRES_DATABASE}
      AUTH_POSTGRES_USER: ${POSTGRES_USERNAME}
      AUTH_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSLMODE: disable
  redis:
    image: "redis:6.0.16-alpine"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
  rabbitmq:
    image: "rabbitmq:3.12-management"
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

volumes:
  pg_data:
  redis_data:
  rabbitmq_data:
  rabbitmq_logs:
