version: '3.8'

services:
  postgres:
    image: postgres:15.3
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_SSLMODE: enable
      AUTH_POSTGRES_DATABASE: ${AUTH_POSTGRES_DATABASE}
      AUTH_POSTGRES_USERNAME: ${AUTH_POSTGRES_USERNAME}
      AUTH_POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
      AUTH_POSTGRES_SCHEMA: ${AUTH_POSTGRES_SCHEMA}
      BACKEND_POSTGRES_DATABASE: ${BACKEND_POSTGRES_DATABASE}
      BACKEND_POSTGRES_USERNAME: ${BACKEND_POSTGRES_USERNAME}
      BACKEND_POSTGRES_PASSWORD: ${BACKEND_POSTGRES_PASSWORD}
      BACKEND_POSTGRES_SCHEMA: ${BACKEND_POSTGRES_SCHEMA}
      GAME_POSTGRES_DATABASE: ${GAME_POSTGRES_DATABASE}
      GAME_POSTGRES_USERNAME: ${GAME_POSTGRES_USERNAME}
      GAME_POSTGRES_PASSWORD: ${GAME_POSTGRES_PASSWORD}
      GAME_POSTGRES_SCHEMA: ${GAME_POSTGRES_SCHEMA}
  redis:
    image: 'redis:6.0.16-alpine'
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3
  # rabbitmq:
  #   image: 'rabbitmq:3.12-management'
  #   ports:
  #     - '${RABBITMQ_PORT}:5672'
  #     - '15672:15672'
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #     - rabbitmq_logs:/var/log/rabbitmq
  auth_nginx:
      image: nginx:latest
      ports:
        - "80:80" 
      volumes:
        - ./auth_ngnix.conf:/etc/nginx/nginx.conf:ro  # Mount the custom nginx.conf
      extra_hosts:
        - "host.docker.internal:host-gateway"  # Access the host machine from the container
volumes:
  postgres_data:
  redis_data:
  # rabbitmq_data:
  rabbitmq_logs:
