#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
    CREATE USER $AUTH_POSTGRES_USER WITH ENCRYPTED PASSWORD '$AUTH_POSTGRES_PASSWORD' CREATEDB;
    CREATE DATABASE $AUTH_POSTGRES_DB;
    GRANT ALL PRIVILEGES ON DATABASE $AUTH_POSTGRES_DB TO $AUTH_POSTGRES_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $AUTH_POSTGRES_USER;
    GRANT ALL ON SCHEMA public to $AUTH_POSTGRES_USER;
EOSQL
