#!/bin/bash
set -e

echo "Creating user \"$AUTH_POSTGRES_USERNAME\" WITH  password ***"

# Create user n database
psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
    CREATE USER $AUTH_POSTGRES_USERNAME WITH ENCRYPTED PASSWORD '$AUTH_POSTGRES_PASSWORD' CREATEDB;
    CREATE DATABASE $AUTH_POSTGRES_DATABASE;
EOSQL

# Exec into database and grant privileges
psql -v ON_ERROR_STOP=1 --username "postgres" $AUTH_POSTGRES_DATABASE <<-EOSQL
    GRANT ALL PRIVILEGES ON DATABASE $AUTH_POSTGRES_DATABASE TO $AUTH_POSTGRES_USERNAME;
    GRANT ALL PRIVILEGES ON SCHEMA $AUTH_POSTGRES_SCHEMA TO $AUTH_POSTGRES_USERNAME;
    GRANT ALL ON SCHEMA public to $AUTH_POSTGRES_USERNAME;
EOSQL

echo "Creating user \"$BACKEND_POSTGRES_USERNAME\" WITH  password ***"

# Create user n database
psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
    CREATE USER $BACKEND_POSTGRES_USERNAME WITH ENCRYPTED PASSWORD '$BACKEND_POSTGRES_PASSWORD' CREATEDB;
    CREATE DATABASE $BACKEND_POSTGRES_DATABASE;
EOSQL

# Exec into database and grant privileges
psql -v ON_ERROR_STOP=1 --username "postgres" $BACKEND_POSTGRES_DATABASE <<-EOSQL
    GRANT ALL PRIVILEGES ON DATABASE $BACKEND_POSTGRES_DATABASE TO $BACKEND_POSTGRES_USERNAME;
    GRANT ALL PRIVILEGES ON SCHEMA $BACKEND_POSTGRES_SCHEMA TO $BACKEND_POSTGRES_USERNAME;
    GRANT ALL ON SCHEMA public to $BACKEND_POSTGRES_USERNAME;
EOSQL

echo "Creating user \"$GAME_POSTGRES_USERNAME\" WITH  password ***"

# Create user n database
psql -v ON_ERROR_STOP=1 --username "postgres" <<-EOSQL
    CREATE USER $GAME_POSTGRES_USERNAME WITH ENCRYPTED PASSWORD '$GAME_POSTGRES_PASSWORD' CREATEDB;
    CREATE DATABASE $GAME_POSTGRES_DATABASE;
EOSQL

# Exec into database and grant privileges
psql -v ON_ERROR_STOP=1 --username "postgres" $GAME_POSTGRES_DATABASE <<-EOSQL
    GRANT ALL PRIVILEGES ON DATABASE $GAME_POSTGRES_DATABASE TO $GAME_POSTGRES_USERNAME;
    GRANT ALL PRIVILEGES ON SCHEMA $GAME_POSTGRES_SCHEMA TO $GAME_POSTGRES_USERNAME;
    GRANT ALL ON SCHEMA public to $GAME_POSTGRES_USERNAME;
EOSQL
