apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{ name }-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: { name }
  template:
    metadata:
      labels:
        app: { name }
    spec:
      containers:
        - name: { name }
          image: { image }
          ports:
            - containerPort: { backend_port }
          envFrom:
            - configMapRef:
                name: "{ name }-configmap"
          env:
            - name: DATA_SOURCE_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: "{ name }-postgres-db-credentials"
                  key: host
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
              ephemeral-storage: 2Gi
            limits:
              cpu: 410m
              memory: "1.5Gi"
              ephemeral-storage: 4Gi
      imagePullSecrets:
        - name: gar
