apiVersion: batch/v1
kind: Job
metadata:
  name: data-source-migration-${UUID}
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: migration
          image: ${IMAGE}
          command:
            [
              "bash",
              "-c",
              "ls -al /app/server/packages/data-source && cd /app/server/packages/data-source && pnpm run migrate",
            ]
          env:
            - name: DATA_SOURCE_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: backend-postgres-db-credentials
                  key: DATA_SOURCE_POSTGRES_URL
      restartPolicy: Never
      imagePullSecrets:
        - name: gar
