apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{ name }-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: { name }
  template:
    metadata:
      labels:
        app: { name }
    spec:
      containers:
        - name: { name }
          image: { image }
          command:
            - "/bin/sh"
          args:
            - "-c"
            - "sleep 1000000"
          envFrom:
            - configMapRef:
                name: "{ name }-configmap"
          ports:
            - containerPort: { backend_port }
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
              ephemeral-storage: 2Gi
            limits:
              cpu: 410m
              memory: "1.5Gi"
              ephemeral-storage: 4Gi
      imagePullSecrets:
        - name: gar
