apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{ name }-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: { name }
  template:
    metadata:
      labels:
        app: { name }
    spec:
      containers:
        - name: { name }
          image: { image }
          envFrom:
            - configMapRef:
                name: "{ name }-configmap"
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: "{ name }-postgres-db-credentials"
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: "{ name }-postgres-db-credentials"
                  key: port
            - name: POSTGRES_DATABASE
              valueFrom:
                secretKeyRef:
                  name: "{ name }-postgres-db-credentials"
                  key: dbname
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{ name }-postgres-db-credentials"
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{ name }-postgres-db-credentials"
                  key: password
          ports:
            - containerPort: { backend_port }
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
              ephemeral-storage: 2Gi
            limits:
              cpu: 410m
              memory: "1.5Gi"
              ephemeral-storage: 4Gi
      imagePullSecrets:
        - name: gar
