apiVersion: batch/v1
kind: Job
metadata:
  name: auth-db-migration-${UUID}
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: migration
          image: ${IMAGE}
          command:
            ["bash", "-c", "sleep 100000"]
          env:
            - name: DATA_SOURCE_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: auth-postgres-db-credentials
                  key: DATA_SOURCE_POSTGRES_URL
      restartPolicy: Never
      imagePullSecrets:
        - name: gar
