import './globals.css';
import type { Metadata } from 'next';
import { Providers } from './providers';
import { Header } from '@/features/header';

export const metadata: Metadata = {
  title: 'Workaround',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main>
            <Header />
          </main>
        </Providers>
      </body>
    </html>
  );
}
