import './globals.css';
import type { Metadata } from 'next';
import { ContainerLayout } from '@wr/ui';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Workaround',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ContainerLayout>{children}</ContainerLayout>
        </Providers>
      </body>
    </html>
  );
}
