import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "../features/providers";
import { Header } from "@/features/header";
import Editor from "@/features/editor/Editor";
import { registerComponents } from "@wr/ui";
import NextLink from "next/link";

registerComponents({
  Link: NextLink,
});

export const metadata: Metadata = {
  title: "Workaround",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
